### ISSUE TITLE
Unknown argument: major

### ISSUE THREAD

**Issue by johnhamm** [radswiat/webpack-auto-inject-version#1]
I installed webpack-auto-inject-version:

`npm install webpack-auto-inject-version --save-dev`

I then run:
`webpack --major`

I get the following error:
`Unknown argument: major`

**Comment by raygers** [comment]
I am getting the same issue. According to webpack, custom arguments is now to be passed through via --env,major. This method is not compatible with the plugin.

It would also  be nice if the "PATH_PACKAGE" and the version property name could be passed in via configuration. In my case, it is different.

Thanks
Ray

**Comment by radswiat** [comment]
It is now possible to pas PATH_PACKAGE ( bare in mind, that the name has change doe! ),
you can overwrite nearly anything from config.js file.
+ plugin from now on use the --env.patch, --env.minor, --env.major

thanks
