### ISSUE TITLE
Remove [AIV]

### ISSUE THREAD

**Issue by fabioricali** [radswiat/webpack-auto-inject-version#16]
Hi,

it's possible remove [AIV] from comment?

**Comment by almothafar** [comment]
It should be an option, but I think it is minor anyway.

**Comment by mvoica** [comment]
mmm I'm thinking react -> jsx, something like 
```

const version = item['someProperty']; 
render() {return <span>{version}</span>}

```
would get... replaced. Which in this case, would not be desired. The [AVI] tag makes the {version} tied to a context which is improbable to be used by something else.

**Comment by radswiat** [comment]
I think original discussion was around AIV protected configuration bit - inside comments and not about [AIV] tag which is necessary as @mvoica pointed out.

From now on, AIV is fully configurable, you can change any config you want,
please take a look into updated README file.

Thanks!
