### ISSUE TITLE
Option to inject {date} into [AIV]{version}[/AIV] like comments

### ISSUE THREAD

**Issue by vincentw56** [radswiat/webpack-auto-inject-version#18]
It would be great to have an option to inject {date} into [AIV]{version}[/AIV] like comments.

Something like `[AIV]{date}[/AIV]` or `[AIV]{version} {date}[/AIV]`.

**Comment by almothafar** [comment]
Indeed, I'm looking for this option as well.

**Comment by mvoica** [comment]
yeah, was just looking at how to extend it for my needs - but seems more ppl have the same issue.

**Comment by radswiat** [comment]
Please take a look into updated README file :)
Thanks!
