### ISSUE TITLE
Reset lower # with each increment

### ISSUE THREAD

**Issue by jhfoo** [radswiat/webpack-auto-inject-version#19]
Wondering if it makes sense to have this option:
To have the option such that when a minor value is increased the patch value is reset (ie 0). Similarly when a major value is increased the minor and patch values are reset.

**Comment by radswiat** [comment]
Hey,
I assumed it already works like that ...
AIV uses `semver` to increase version depending on release type.
https://github.com/npm/node-semver

Maybe i'm doing it wrong - i'll double check that :)

Thanks!
