### ISSUE TITLE
InjectAsComment not injecting into index.html

### ISSUE THREAD

**Issue by tonybranfort** [radswiat/webpack-auto-inject-version#21]
Hi - Thanks for the module.  It does what I primarily needed - getting the package version number into the webpack dist bundle.  But, just reporting that it isn't adding the comment to my index.html file using the config shown below.  

After running, nothing is added or different in my index.hml.  

bundle.js has the comment ```// [AIV]  Version: 2.4.0 - 9:36:36 AM``` (not sure why it doesn't have NAME?) as expected. 

Using webpack 3.7.1 .  

```javascript
    new WebpackAutoInject({
      NAME: 'idb-ng',
      SILENT: true,
      PACKAGE_JSON_PATH: './package.json',
      components: {InjectAsComment: true},
      componentsOptions: {
        InjectAsComment: {
          tag: 'Version: {version} - {date}',
          dateFormat: 'h:MM:ss TT'
        },        
      }
    })
```

**Comment by rkalicinski** [comment]
Looks like NAME property is not supported in the code, use SHORT property instead and that way you will get [idb-ng] instead of [AIV].
