### ISSUE TITLE
Apply shouldn't be executed asynchroneously

### ISSUE THREAD

**Issue by rkalicinski** [radswiat/webpack-auto-inject-version#22]
There is a problem related to the fact that WebpackAutoInject.apply method and all following calls are done asynchronously. Currently there is no control over sequence of registering of 'emit' functions by InjectAsComment and InjectByTag.
I use another plugin compression-webpack-plugin that compresses js files at the end of bundle building flow.
Current behavior looks as follows:
1) InjectAsComment appends version in comment to bundle.js,
2) compress plugin compresses bundle.js to bundle.js.bz,
3) InjectByTag replaces version tag in source code of bundle.js.
In result I get bundle.js that contains generated version in place of [AIV] tag and bundle.js.bz that hasn't got [AIV] tag replaced.

**Comment by rkalicinski** [comment]
Please, look at my PR. I really need this to be fixed in official module version in npm.

**Comment by chabou-san** [comment]
I've also created a PR where asynchronous mode is kept, but fixed so as to work with compression-webpack-plugin.

**Comment by radswiat** [comment]
Hey guys,
big thank you for help and PR - I did some modifications on that + I checked if it works with the compression-webpack-plugin and it does. One thing to keep in mind is the order of the webpack plugins, as webpack-auto-inject-version has to be before anything else in webpack.plugins config.
