### ISSUE TITLE
Not working with query hash on filename

### ISSUE THREAD

**Issue by patric-eberle** [radswiat/webpack-auto-inject-version#25]
I have a setup where the `chunkhash` is added to the file name as a query (e.g. `app.js?12345`). Unfortunately this breaks the version injection as comment. Injection by tag still seems to work.

My webpack output config: 

```JavaScript
output: {
      path: path.resolve(__dirname, 'dist'),
      filename: `${assetsSubDirectory}js/[name].js?[chunkhash]`,
      chunkFilename: `${assetsSubDirectory}js/[id].js?[chunkhash]`,
      publicPath: '/', // Public path to 'dist' scope in production
}
``` 
Plugin
```JavaScript
new WebpackAutoInject({
        SILENT: true,
        components: {
          AutoIncreaseVersion: false,
          InjectAsComment: true,
          InjectByTag: true
        },
        componentsOptions: {
          InjectAsComment: {
            tag: 'Build version: {version} - {date}',
            dateFormat: 'dddd, mmmm d, yyyy, hh:MM:ss'
          }
        }
})
```

**Comment by patric-eberle** [comment]
Can be tested here: https://github.com/patric-eberle/vue-template

**Comment by radswiat** [comment]
fixed now :) 
`path.extname(basename).replace(/(\?)(.){0,}/, '');`

path.extname was ignoring ?random in the file name, so instead of giving back just the extension,
it was returning the extension WITH the ?param
