### ISSUE TITLE
InjectByTag not working with interior comma

### ISSUE THREAD

**Issue by richard-edwards** [radswiat/webpack-auto-inject-version#28]
This is in a .vue file, not sure if it behaves the same way in other files or not.

## Steps to reproduce:

* add the following to html file
```
[AIV]Version {version} , {date}[/AIV]
```
## Expected outcome:
* html contains ```Version 01.00.00 , Jan 15th, 2018```

## Actual outcome:
* html contains ```[AIV]Version {version} , {date}[/AIV]```

**Comment by radswiat** [comment]
Fixed, thanks for help!
( it was regExp issue, also it is now possible to modify this regex in the config file in case of any similar issue in the future "AIVTagRegexp" )
