### ISSUE TITLE
Document fileRegex setting and NAME, SHORT

### ISSUE THREAD

**Issue by richard-edwards** [radswiat/webpack-auto-inject-version#29]
I couldn't find any documentation on the fileRegex parameter for InjectByTag. Does this just check the files specified that match the regex for the [AIV] tag?

Also, what are the NAME and SHORT settings for?

Really like this plugin so far, thanks.

**Comment by radswiat** [comment]
Hey, thanks!

As of new version, NAME has been removed ;)
SHORT description was added into README.md,

short is a tag that will be injected into you comment block eg:
[AIV] Version: ....
if you will change SHORT you can change [AIV] to anything custom eg [CUSTOM]

**Comment by richard-edwards** [comment]
Also wondering about fileRegex parameter? Thanks for the help.
