### ISSUE TITLE
Issue to while adding version to build files

### ISSUE THREAD

**Issue by kguruprokarma** [radswiat/webpack-auto-inject-version#3]
@radswiat : I followed the steps suggested, installed webpack-auto-inject-version, and updated the start with webpack --major, and in webpack.config.js (which is my build configuration file) i want to append the build version to the files. but am unable to do the same, can you help me if there is anything am missing.

**Comment by radswiat** [comment]
There will be a new version coming in soon, but can you clarify what u mean by that:
` i want to append the build version to the files. but am unable to do the same, can you help me if there is anything am missing.`

Where do you try to append the build version ? By auto inject or by tag ? And can u give some example ?

thanks
