### ISSUE TITLE
AIV doesn't output log according to npm's loglevel config.

### ISSUE THREAD

**Issue by Craignewkirk** [radswiat/webpack-auto-inject-version#33]
Hello,

This issue is fairly self-explanatory.  If I add any loglevel above info, for example:

loglevel = error

to a project's .npmrc file, AIV still posts 'info' warnings.  

Depending on the project, this can contribute to maxbuffer issues.

**Comment by radswiat** [comment]
Should be ok from next version `npm start -s` will disable console logs
