### ISSUE TITLE
Requested Feature: Inject as JS comment, add option for injecting `/* */` comments

### ISSUE THREAD

**Issue by mlinvilleengler** [radswiat/webpack-auto-inject-version#34]
Hi,
Great plugin.
What do you think of adding an option to inject js comments wrapped in /* */ or just making it the default nature.
We have a use case where we inject a js file to an html file so the // comment will break the file.
Let me know your thoughts, I can submit a pr.

**Comment by radswiat** [comment]
thanks for comment, it make sense :) should be available with the next version
