### ISSUE TITLE
Ability to set timezone

### ISSUE THREAD

**Issue by alecrae** [radswiat/webpack-auto-inject-version#36]
It would be great to be able to set the timezone for the date output, do you know if it's currently possible? My use case is my build server is in a different timezone so it's time is irrelevant to me

**Comment by radswiat** [comment]
Hey,
actually there is :) Thanks for asking, i'll add this into the documentation

`UTC:h:MM:ss` or `GMT:h:MM:ss`

**Comment by Kaidash** [comment]
@radswiat Could I set time zone like?
`            dateFormat: 'GMT+1:h:MM:ss'
`
or

`            dateFormat: 'GMT+0500:h:MM:ss'
`

**Comment by ustun** [comment]
@Kaidash See https://www.npmjs.com/package/dateformat
