### ISSUE TITLE
Customize Tag?

### ISSUE THREAD

**Issue by Skaronator** [radswiat/webpack-auto-inject-version#5]
Would be nice if you could add a option to customize the tag.

`<!-- [AIV] Build version: 0.0.1 -->`

Maybe by adding something like this:
Default: `[AIV] Build version: {version}`
Custom: `example.com - Build: {version} - Compiled: {buildDate}`

{buildDate} could be `"Mon Nov 23 2015 14:26:25 GMT+0100 (CET)"`

**Comment by radswiat** [comment]
sure!

**Comment by radswiat** [comment]
done :)

**Comment by Skaronator** [comment]
Thanks!
Maybe it would be better to use ISO 8061 for the dates.

`2007-08-31T16:47+00:00`
https://en.wikipedia.org/wiki/ISO_8601

And maybe the ability to customize it.
